Repository Cog-Creators/Red-Dashboard, pull requests merged in 2020-10, with the labels that each got.

#26 [Develop] 0.1.6a.dev
  babel.cfg
  reddash/app/base/routes.py
  reddash/app/base/templates/base-site.html
  reddash/app/base/templates/login/login.html
  reddash/app/constants.py
  reddash/app/home/routes.py
  reddash/app/home/templates/credits.html
  reddash/app/home/templates/third_party/spotify.html
  reddash/app/utils.py
  setup.py
Labels: hacktoberfest-accepted

#30 It hurt (Typo fix)
  reddash/app/home/templates/third_party/spotify.html
Labels: hacktoberfest-accepted

#34 Update labels in Crowdin integration
  .github/workflows/publish_crowdin.yaml
Labels: 1-area-meta, 2-type-bug/fix

#35 Updated issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 0-status-accepted, 1-area-meta, 2-type-enhancement, hacktoberfest-accepted
